services:
  app:
    image: 'ammezie/postie:latest'
    volumes:
      - '.:/home/node/app'
    environment:
      TZ: ${TZ}
      PORT: ${PORT}
      HOST: ${HOST}
      LOG_LEVEL: ${LOG_LEVEL}
      APP_KEY: ${APP_KEY}
      NODE_ENV: ${NODE_ENV}
      APP_URL: ${APP_URL}
      SESSION_DRIVER: ${SESSION_DRIVER}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      QUEUE_REDIS_HOST: ${QUEUE_REDIS_HOST}
      QUEUE_REDIS_PORT: ${QUEUE_REDIS_PORT}
      QUEUE_REDIS_PASSWORD: ${QUEUE_REDIS_PASSWORD}
    ports:
      - '${PORT:-3333}:3333'
    command: 'node bin/server.js'

  worker:
    image: 'ammezie/postie:latest'
    volumes:
      - '.:/home/node/app'
    environment:
      TZ: ${TZ}
      PORT: ${WORKER_PORT}
      HOST: ${HOST}
      LOG_LEVEL: ${LOG_LEVEL}
      APP_KEY: ${APP_KEY}
      NODE_ENV: ${NODE_ENV}
      APP_URL: ${APP_URL}
      SESSION_DRIVER: ${SESSION_DRIVER}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      QUEUE_REDIS_HOST: ${QUEUE_REDIS_HOST}
      QUEUE_REDIS_PORT: ${QUEUE_REDIS_PORT}
      QUEUE_REDIS_PASSWORD: ${QUEUE_REDIS_PASSWORD}
    ports:
      - '${WORKER_PORT:-4444}:4444'
    command: ['node', '/home/node/app/ace', 'queue:listen']
